Repository WorldHealthOrganization/smart-trust-network-gateway, pull requests merged in 2022-03, with the labels that each got.

#34 Feat: Add DDCCG Downloader
  pom.xml
  src/main/java/eu/europa/ec/dgc/gateway/repository/TrustedIssuerRepository.java
  src/main/java/eu/europa/ec/dgc/gateway/repository/TrustedReferenceRepository.java
  src/main/java/eu/europa/ec/dgc/gateway/restapi/dto/TrustedIssuerDto.java
  src/main/java/eu/europa/ec/dgc/gateway/restapi/mapper/GwTrustListMapper.java
  src/main/java/eu/europa/ec/dgc/gateway/service/SignerInformationService.java
  src/main/java/eu/europa/ec/dgc/gateway/service/TrustedIssuerService.java
  src/main/java/eu/europa/ec/dgc/gateway/service/TrustedReferenceService.java
  src/main/java/eu/europa/ec/dgc/gateway/service/federation/downloaderimplementations/DdccgDownloader.java
  src/main/java/eu/europa/ec/dgc/gateway/service/federation/downloaderimplementations/LegacyDgcgDownloader.java
Labels: enhancement

#35 add missing transactional on TrustedReferenceRepository
  src/main/java/eu/europa/ec/dgc/gateway/repository/TrustedReferenceRepository.java
  src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustedReferenceIntegrationTest.java
Labels: bug

#39 Several Fixes
  pom.xml
  src/main/java/eu/europa/ec/dgc/gateway/restapi/filter/CertificateAuthenticationFilter.java
  src/main/java/eu/europa/ec/dgc/gateway/service/SignerInformationService.java
  src/main/java/eu/europa/ec/dgc/gateway/service/TrustedIssuerService.java
  src/main/java/eu/europa/ec/dgc/gateway/service/TrustedPartyService.java
  src/main/java/eu/europa/ec/dgc/gateway/service/TrustedReferenceService.java
  src/main/java/eu/europa/ec/dgc/gateway/service/federation/downloaderimplementations/DdccgDownloader.java
  src/main/java/eu/europa/ec/dgc/gateway/service/federation/downloaderimplementations/LegacyDgcgDownloader.java
Labels: bug, enhancement

#36 feat: enable heatlh check
  kubernetes/gateway/deployment.yml
  src/main/resources/application.yml
Labels: enhancement

#43 Fix: Add URL to TrustedReference
  pom.xml
  src/main/java/eu/europa/ec/dgc/gateway/entity/TrustedReferenceEntity.java
  src/main/java/eu/europa/ec/dgc/gateway/restapi/dto/TrustedReferenceDto.java
  src/main/java/eu/europa/ec/dgc/gateway/service/TrustedReferenceService.java
  src/main/java/eu/europa/ec/dgc/gateway/service/federation/downloaderimplementations/DdccgDownloader.java
  src/main/resources/db/changelog.xml
  src/main/resources/db/changelog/add-trusted-reference-url-column.xml
  src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustedReferenceIntegrationTest.java
  src/test/resources/application.yml
Labels: bug

#44 Fix: Trusted Reference Delete Country
  src/main/java/eu/europa/ec/dgc/gateway/service/TrustedReferenceService.java
  src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustedReferenceIntegrationTest.java
Labels: bug
